// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8upGbOd3g0ZfOZJTxWgHQpntLYCzQBNw',
    appId: '1:453751069999:web:ec2a225b2b592b647155da',
    messagingSenderId: '453751069999',
    projectId: 'profile-book-dde34',
    authDomain: 'profile-book-dde34.firebaseapp.com',
    databaseURL: 'https://profile-book-dde34-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'profile-book-dde34.appspot.com',
    measurementId: 'G-RVWT28XD1G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOmuTrqOLoGz4XhxnoeI8l-r4retNK-wI',
    appId: '1:453751069999:android:dac85a1e6943cd677155da',
    messagingSenderId: '453751069999',
    projectId: 'profile-book-dde34',
    databaseURL: 'https://profile-book-dde34-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'profile-book-dde34.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANupXwABgA4HVleWSsGi7qjFmPI6bH9t4',
    appId: '1:453751069999:ios:c35253988027df677155da',
    messagingSenderId: '453751069999',
    projectId: 'profile-book-dde34',
    databaseURL: 'https://profile-book-dde34-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'profile-book-dde34.appspot.com',
    iosBundleId: 'com.example.profileBookFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyANupXwABgA4HVleWSsGi7qjFmPI6bH9t4',
    appId: '1:453751069999:ios:f9068def1bf6c5ad7155da',
    messagingSenderId: '453751069999',
    projectId: 'profile-book-dde34',
    databaseURL: 'https://profile-book-dde34-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'profile-book-dde34.appspot.com',
    iosBundleId: 'com.example.profileBookFlutter.RunnerTests',
  );
}
